// DO NOT CHANGE ANY COMMENTS HERE......
//_sample.js

// Create a function sum() that returns the sum of the two numbers passed as its arguments.
// For example, sum(2,5) should return 7; sum(3,10) should return 13.

function sum(num1, num2) {
    //code here
}

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// You can use this space below to console log but you must delete it after
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Test Cases (4/4)
// sum(3,2) to return 5
// sum(3,10) to return 13
// sum(-3,4) to return 1
// sum(-5,10) to return 5

//Don't touch the export below
export { sum };
