// DO NOT CHANGE ANY COMMENTS HERE......
//problem3

// Given an array, write a function that changes all positive numbers in the array to “big”.
// Example: makeItBig([-1,3,5,-5]) returns that same array, changed to [-1,"big","big",-5].

function makeItBig(arr) {
    //code here
}

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// You can use this space below to console log but you must delete it after
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Test Cases (3/3)
// makeItBig([-1,3,5,-5]) to return [-1,"big","big",-5]
// makeItBig([2,4,6]) to return ["big","big","big"]
// makeItBig([-4,0,4]) to return [-4,0,"big"]

//Don't touch the export below
export { makeItBig };
