// DO NOT CHANGE ANY COMMENTS HERE......
//problem5

// Given an array and a value Y, count and return the number of array values greater than Y.
// For example, returnArrayCountGreaterThanY( [2,3,5], 4) should return 1 as there is only one element in the array whose value is greater than 4.

function returnArrayCountGreaterThanY(arr, y) {
    // code here
}

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// You can use this space below to console log but you must delete it after
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Test Cases (4/4)
// returnArrayCountGreaterThanY( [2,3,5], 4) to return 1
// returnArrayCountGreaterThanY( [2,3,5], 1) to return 3
// returnArrayCountGreaterThanY( [4,10,15], 10) to return 1
// returnArrayCountGreaterThanY( [4,10,15], 20) to return 0

//Don't touch the export below
export { returnArrayCountGreaterThanY };
