// DO NOT CHANGE ANY COMMENTS HERE......
//problem8

// Given an array, swap first and last, second and second-to-last, third and third-to-last, etc. Have the function return this swapped array.
// For example, swapTowardCenter([true,42,"Ada",2,"pizza"]) should return ["pizza",2,"Ada",42,true]. Passing [1,2,3,4,5,6] should return [6,5,4,3,2,1].

function swapTowardCenter(arr) {
    //Code here
}

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// You can use this space below to console log but you must delete it after
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Test Cases (3/3)
// swapTowardCenter([true,42,"Ada",2,"pizza"]) to return ["pizza",2,"Ada",42,true]
// swapTowardCenter([1,2,3,4,5,6]) to return [6,5,4,3,2,1]
// swapTowardCenter(["hi", "coding", "dojo", "fans"]) to return ["fans","dojo","coding","hi"]

//Don't touch the export below
export { swapTowardCenter };
