// DO NOT CHANGE ANY COMMENTS HERE......
//problem14

// Return the second-to-last element of an array. Given [42,true,4,"Kate",7], return "Kate". If array is too short, return null.

function secondToLast(arr) {
    //Code here
}

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// You can use this space below to console log but you must delete it after
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Test Cases (4/4)
// secondToLast( [42,true,4,"Kate",7] ) to return Kate
// secondToLast([42,true,4,"Kate",7, 9] ) to return 7
// secondToLast([42,true,4,"Kate",7, 9, "dojo", "awesome"]) to return dojo
// secondToLast([1]) to return null

//Don't touch the export below
export { secondToLast };
