// DO NOT CHANGE ANY COMMENTS HERE......
//problem13

// Replicate JavaScript’s concat(). Create a standalone function that accepts two arrays. Return a new array containing the first array’s elements, followed by the second array’s elements. Do not alter the original arrays.
// Ex.: arrConcat( ['a','b'], [1,2] ) should return a new array ['a','b',1,2].

function arrayConcat(arr1, arr2) {
    //Code here
}

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// You can use this space below to console log but you must delete it after
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Test Cases (4/4)
// arrayConcat([1,2], [3,4]) to return [1,2,3,4]
// arrayConcat([1,2], [3,4,5]) to return [1,2,3,4,5]
// arrayConcat([1,2,3], [3,4,5,6]) to return [1,2,3,3,4,5,6]
// arrayConcat([ -1 ], [ -5, 3 ]) to return [-1,-5,3]

//Don't touch the export below
export { arrayConcat };
