// DO NOT CHANGE ANY COMMENTS HERE......
//problem12

// Alan is good at breaking secret codes. One method is to eliminate values that lie within a specific known range. Given arr and values min and max, retain only the array values between min and max. Work in-place: return the array you are given, with values in the original order. No built-in array functions.

function filterRange(arr, min, max) {
    //Code here
}

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// You can use this space below to console log but you must delete it after
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Test Cases (5/5)
// filterRange([1,3,5,7,10], 4, 8) to return [5,7]
// filterRange([1,3,5,7,10], -1, 4) to return [1,3]
// filterRange([2,4,3,5], 2, 6) to return [4,3,5]
// filterRange([2,4,3,5], 0, 4) to return [2,3]
// filterRange([6,2,-3,5,7], 3, 8) to return [6,5,7]

//Don't touch the export below
export { filterRange };
