// DO NOT CHANGE ANY COMMENTS HERE......
//problem11

// Return whether a given integer is prime. Prime numbers are only evenly divisible by themselves and 1. Many highly optimized solutions exist, but for now, just create one that is easy to understand and debug.
// For example, isPrime(3) should return true. isPrime(4) should return false as 4 is divisible by 2.

function isPrime(num) {
    //Code here
}

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// You can use this space below to console log but you must delete it after
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Test Cases (5/5)
// isPrime(3) to return true
// isPrime(4) to return false
// isPrime(13) to return true
// isPrime(65) to return false
// isPrime(17) to return true

//Don't touch the export below
export { isPrime };
