// DO NOT CHANGE ANY COMMENTS HERE......
//problem4

// Given an array, create a function to return a new array where each value in the original has been doubled. Calling double([1,2,3]) should return [2,4,6].

function double(arr) {
    //code here
}

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// You can use this space below to console log but you must delete it after
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Test Cases (3/3)
// double([1,2,3]) to return [2,4,6]
// double([-2, 0, 2]) to return [-4,0,4]
// double([2,10,100]) to return [4,20,200]

//Don't touch the export below
export { double };
