// DO NOT CHANGE ANY COMMENTS HERE......
//problem15

// Create a standalone function that accepts two arrays and combines their values sequentially into a new array, at alternating indices starting with the first array. Extra values from either array should be included afterward.
// Given [1,2] and [10,20,30,40], return new array containing [1,10,2,20,30,40].

function zipIt(arr1, arr2) {
    //Code here
}

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// You can use this space below to console log but you must delete it after
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
//console log here......
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Test Cases (5/5)
// zipIt([1,2], [10,20,30,40 ]) to return [1,10,2,20,30,40]
// zipIt([1,2,3,4], [10,20 ]) to return [1,10,2,20,3,4]
// zipIt([1,2,3,4], [10,20,30,40 ]) to return [1,10,2,20,3,30,4,40]
// zipIt([1], [10,20 ]) to return [1,10,20]
// zipIt([1,2,3], [10 ]) to return [1,10,2,3]

//Don't touch the export below
export { zipIt };
